export const CURRENTSCRITTURADATETEXT = 'Data Registrazione: ';
export const INITIALDATETEXT = 'Data iniziale';
export const FINALDATETEXT = 'Data finale';
export const POSITIONEDACCOUNTSTEXT = 'Account posizionati: ';
export const SAVEMODIFICATIONSTEXT = 'Salva modifiche';
export const CANCELMODIFICATIONSTEXT = 'Annulla modifiche';
export const DELETEACCOUNTTEXT = 'Cancella account';
export const SELECTBARCOLORTEXT = 'Seleziona colore barra:';
export const SELECTACCOUNTCOLORTEXT = 'Seleziona colore scritta: ';
export const SELECTACCOUNTBACKGROUNDCOLORTEXT = 'Seleziona colore account: ';
export const FILEUPLOADFINISHED = 'Caricamento completato';
export const SELECTBACKGROUNDCOLORTEXT = 'Seleziona colore sfondo: ';
export const SHOWPROGRESSBARCHECKBOXTEXT = "Mostra barra percentuale su totale";
export const ANIMATIONDURATIONTEXTBOXLABELTEXT = "Durata singola animazione (ms)";
export const ANIMATIONDELAYTEXTBOXLABELTEXT = "Intervallo partenza animazioni (ms)";
export const ANIMATIONDURATIONTEXTBOXTOOLTIPTEXT = "Inserire quanto tempo passa dalla creazione alla cancellazione dei pallini, in millisecondi";
export const ANIMATIONDELAYTEXTBOXTOOLTIPTEXT = "Inserire l'intervallo di tempo tra la partenza di un'animazione e l'altra, in millisecondi";
export const LOWANIMATIONDELAYWARNINGTEXT = "L'intervallo di tempo tra le partenze di due animazioni è molto basso, la durata prevista è probabilmente minore di quella reale"
export const LOADSAVECONFIGURATIONTEXT = "Carica/salva configurazione: "
export const SELECTANIMATIONMODALITY = "Seleziona modalità riproduzione: "